
// <auto-generated/>
// Do not modify by hand!
// To update this file, use "Tools -> UnityCodeGen -> Generate" main menu item

using System;
using Newtonsoft.Json;
using CherryFramework.DataModels;
using CherryFramework.DataModels.Templates;

namespace GeneratedDataModels
{
    [Serializable]
    public class ExampleDataModel : DataModelBase
    {
        private ExampleData _template = new();
        
        public ExampleDataModel() : base()
        {
			Getters.Add(nameof(Foo), new Func<System.String>(() => Foo));
			Setters.Add(nameof(Foo), new Action<System.String>(o => Foo = o));
			FooAccessor = new Accessor<System.String>(this, nameof(Foo));


        }
		
		public ExampleDataModel(ExampleData source) : this()
        {
	        if (source != null)
	        {
		        if (source is ICloneable cloneable)
		        {
			        _template = cloneable.Clone() as ExampleData;
		        }
		        else
		        {
			        throw new ArgumentException($"[{this.GetType().Name}] Tried to create new model with template source, but source is not ICloneable, which is not allowed!");
		        }
	        }
	        else
	        {
		        throw new ArgumentNullException(nameof(source));
	        }
        }
        
        // ReSharper disable InconsistentNaming

        public System.String Foo
        {
            get => _template.Foo;
            set { _template.Foo = value;
            Send<System.String>(nameof(Foo), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.String> FooAccessor;

        // ReSharper restore InconsistentNaming
    }
}
