
// <auto-generated/>
// Do not modify by hand!
// To update this file, use "Tools -> UnityCodeGen -> Generate" main menu item

using System;
using Newtonsoft.Json;
using CherryFramework.DataModels;
using Sample.Scripts.DataModels.Templates;

namespace GeneratedDataModels
{
    [Serializable]
    public class GameStateDataModel : DataModelBase
    {
        private GameStateData _template = new();
        
        public GameStateDataModel() : base()
        {
			Getters.Add(nameof(GameSpeed), new Func<System.Single>(() => GameSpeed));
			Setters.Add(nameof(GameSpeed), new Action<System.Single>(o => GameSpeed = o));
			GameSpeedAccessor = new Accessor<System.Single>(this, nameof(GameSpeed));

			Getters.Add(nameof(PlayerDead), new Func<System.Boolean>(() => PlayerDead));
			Setters.Add(nameof(PlayerDead), new Action<System.Boolean>(o => PlayerDead = o));
			PlayerDeadAccessor = new Accessor<System.Boolean>(this, nameof(PlayerDead));


        }
		
		public GameStateDataModel(GameStateData source) : this()
        {
	        if (source != null)
	        {
		        if (source is ICloneable cloneable)
		        {
			        _template = cloneable.Clone() as GameStateData;
		        }
		        else
		        {
			        throw new ArgumentException($"[{this.GetType().Name}] Tried to create new model with template source, but source is not ICloneable, which is not allowed!");
		        }
	        }
	        else
	        {
		        throw new ArgumentNullException(nameof(source));
	        }
        }
        
        // ReSharper disable InconsistentNaming

        public System.Single GameSpeed
        {
            get => _template.GameSpeed;
            set { _template.GameSpeed = value;
            Send<System.Single>(nameof(GameSpeed), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Single> GameSpeedAccessor;

        public System.Boolean PlayerDead
        {
            get => _template.PlayerDead;
            set { _template.PlayerDead = value;
            Send<System.Boolean>(nameof(PlayerDead), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Boolean> PlayerDeadAccessor;

        // ReSharper restore InconsistentNaming
    }
}
