
// <auto-generated/>
// Do not modify by hand!
// To update this file, use "Tools -> UnityCodeGen -> Generate" main menu item

using System;
using Newtonsoft.Json;
using CherryFramework.DataModels;
using Sample.DataModels.Templates;

namespace GeneratedDataModels
{
    [Serializable]
    public class GameStatisticsModel : DataModelBase
    {
        private GameStatistics _template;
        
        public GameStatisticsModel() : base()
        {
			_template = new();
			Getters.Add(nameof(GameRunning), new Func<System.Boolean>(() => GameRunning));
			Setters.Add(nameof(GameRunning), new Action<System.Boolean>(o => GameRunning = o));
			GameRunningAccessor = new Accessor<System.Boolean>(this, nameof(GameRunning));

			Getters.Add(nameof(MaxDistance), new Func<System.Int32>(() => MaxDistance));
			Setters.Add(nameof(MaxDistance), new Action<System.Int32>(o => MaxDistance = o));
			MaxDistanceAccessor = new Accessor<System.Int32>(this, nameof(MaxDistance));

			Getters.Add(nameof(TotalRunTime), new Func<System.Int32>(() => TotalRunTime));
			Setters.Add(nameof(TotalRunTime), new Action<System.Int32>(o => TotalRunTime = o));
			TotalRunTimeAccessor = new Accessor<System.Int32>(this, nameof(TotalRunTime));

			Getters.Add(nameof(TotalDistance), new Func<System.Int32>(() => TotalDistance));
			Setters.Add(nameof(TotalDistance), new Action<System.Int32>(o => TotalDistance = o));
			TotalDistanceAccessor = new Accessor<System.Int32>(this, nameof(TotalDistance));

			Getters.Add(nameof(TriesNum), new Func<System.Int32>(() => TriesNum));
			Setters.Add(nameof(TriesNum), new Action<System.Int32>(o => TriesNum = o));
			TriesNumAccessor = new Accessor<System.Int32>(this, nameof(TriesNum));


        }
		
		public GameStatisticsModel(GameStatistics source) : this()
        {
	        if (source != null)
	        {
		        if (source is ICloneable cloneable)
		        {
			        _template = cloneable.Clone() as GameStatistics;
		        }
		        else
		        {
			        throw new ArgumentException($"[{this.GetType().Name}] Tried to create new model with template source, but source is not ICloneable, which is not allowed!");
		        }
	        }
	        else
	        {
		        throw new ArgumentNullException(nameof(source));
	        }
        }
        
        // ReSharper disable InconsistentNaming

        public System.Boolean GameRunning
        {
            get => _template.GameRunning;
            set { _template.GameRunning = value;
            Send<System.Boolean>(nameof(GameRunning), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Boolean> GameRunningAccessor;

        public System.Int32 MaxDistance
        {
            get => _template.MaxDistance;
            set { _template.MaxDistance = value;
            Send<System.Int32>(nameof(MaxDistance), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Int32> MaxDistanceAccessor;

        public System.Int32 TotalRunTime
        {
            get => _template.TotalRunTime;
            set { _template.TotalRunTime = value;
            Send<System.Int32>(nameof(TotalRunTime), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Int32> TotalRunTimeAccessor;

        public System.Int32 TotalDistance
        {
            get => _template.TotalDistance;
            set { _template.TotalDistance = value;
            Send<System.Int32>(nameof(TotalDistance), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Int32> TotalDistanceAccessor;

        public System.Int32 TriesNum
        {
            get => _template.TriesNum;
            set { _template.TriesNum = value;
            Send<System.Int32>(nameof(TriesNum), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Int32> TriesNumAccessor;

        // ReSharper restore InconsistentNaming
    }
}
